# Generated by Django 3.0.7 on 2020-07-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liked',
            old_name='liked',
            new_name='post',
        ),
    ]
