# Generated by Django 3.0.7 on 2020-07-09 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20200709_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Following',
            new_name='Follow',
        ),
        migrations.RenameModel(
            old_name='Followers',
            new_name='Follower',
        ),
    ]
